-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJL5Jlqsgjv7nBCww
kkFZg6YiGdxKrWUbj+B5gjA6pQCgCgYIKoZIzj0DAQehRANCAAQl2LZyrqurkHrJ
+0m/d4BSuLW27qxbtxt69hhDVXEHhYPj74qQ5LKAzXy9qSANlmCnvdbU0hUEiVI4
TgnK1KVQ
-----END PRIVATE KEY-----
